### ISSUE TITLE
"If GitHub were open source itself"

### ISSUE THREAD

**Issue by chris-kahn** [dear-github/dear-github#116]
You realize that there are open-source alternatives with very similar functionality like GitLab?

Nobody is forcing y'all to use the private, closed-source service that is GitHub.

**Comment by dantoac** [comment]
Github strongest point is its userbase, not the software itself (altought is good). That said, I will put this here: https://about.gitlab.com/2016/01/15/making-gitlab-better-for-large-open-source-projects/

**Comment by dabockster** [comment]
Many users (myself included) use GitHub more for the userbase as opposed to functionality. That being said, we tend to defend a lot of, dare I say, _lacking_ services based on that argument. (In other words, why take the huge effort of shifting a large amount of projects to another service when the necessary userbase is already here?)

It's sort of an ugly cycle. Service gets good, users flock to said service. Service gets bad, users are either trapped or the community is fractured. Users only leave once another service starts to eclipse the number of active users on the entrenched service. I've seen this happen on so many sites and services.

**Comment by joeyespo** [comment]
@dabockster Completely agree with this.

Any ideas or articles that talk about how to prevent this?

[This article on using protocols instead of platforms](https://www.techdirt.com/articles/20150717/11191531671/protocols-instead-platforms-rethinking-reddit-twitter-moderation-free-speech.shtml) is the closest thing to a solution I've seen yet. Unfortunately, companies aren't really motivated to produce protocols since it's more work and could potentially hurt the business. I'm really curious about this topic.
