### ISSUE TITLE
Please stop calling `issues` to every single task, not all of them are issues really.

### ISSUE THREAD

**Issue by jgtoriginal** [dear-github/dear-github#272]
Guys, I'm not sure if I'm from planet Earth and you from Mars or the other way around.
But it's awfully wrong to call every single task an **issue**, cause issue in plain old english is something that's going wrong.
Me for instance, as most of GH users, spend a whole amount of my day writing software from scratch. And most of my daily tasks are actually **desired** functionality. And me creating them is actually not an **issue** but a **blessing** for my team. And calling them all issues is just not right, it gives a negative meaning to every single task.
So I'd strongly suggest to call them all **tasks** or **tickets** or anything similar, as long as it implies a positive meaning, and give the option to users to label them as **issues** if that's the case at any point.

**Comment by koenpunt** [comment]
![image](https://user-images.githubusercontent.com/351038/32690797-b14141d8-c6fc-11e7-8fb3-14b3bd16fb44.png)

> an important topic or problem

So IMO "Issue" is just fine.

**Comment by koenpunt** [comment]
Also tasks would insinuate that they're all actionable, which probably isn't the case eithe..

**Comment by jgtoriginal** [comment]
@koenpunt if you go to the oxford dictionary you will find something else. Actually the word problem is all over the places on its first definition. But let dictionaries apart for a moment and imagine you boss walks in towards your desk and tells you: 'Koen we got an issue...' the first thing it comes to your mind is **problem**, right??
So you see exactly what's my point. Among all it's synonyms, 'issue' is not the best for describing a task that is not necessarily a problem. You could use task (although you don't like it), item, points, etc.
**issue** is just not the best.

<img width="736" alt="screen shot 2017-11-12 at 7 40 41 pm" src="https://user-images.githubusercontent.com/1785392/32702128-4a377fc0-c7e2-11e7-85e5-21d7c292de60.png">

**Comment by bderiso** [comment]
Dictionary definitions aside:

1. In common English usage, issue does not necessarily mean problem. Words are flexible like that.
2. Lots of systems and communities have quirky non-standard terms compared to other systems and general use. Consider this: what does "tweet" mean to you? 

Finally, my personal opinion: it's pretty short-sighted to call something "wrong" just because you don't agree with it. What actual useful benefit will changing such an ingrained term bring at this point? It's "wrong" to make changes when there is no good reason.
