### ISSUE TITLE
Structured Voting

### ISSUE THREAD

**Issue by nikolay** [dear-github/dear-github#55]
Up-down voting is an ancient concept. Switch to Emoji Reactions (ala Stack) instead.

**Comment by thejameskyle** [comment]
This ignores filtering/sorting by votes. I don't want to sort by number of :cocktail: or :racehorse:

**Comment by petetnt** [comment]
I don't want down voting for issues in general. If someone has a legitimate issue (or an issue worth reporting in the first place) that is bothering the user, then the last thing I would like to see is someone just down voting the said issue just because the said person a) doesn't have the issue b) doesn't think the issue is significant c) to bump up the urgency of some other issue.

:+1:'s, like the `README.md` states, *serve a valuable function in letting maintainers know how widespread an issue is*. Just doing :-1: however doesn't serve any functionality on it's own.

**Comment by thejameskyle** [comment]
> Just doing :-1: however doesn't serve any functionality on it's own.

It does when looking for community feedback about a change.

**Comment by petetnt** [comment]
@thejameskyle Fair enough, I was mostly talking about issues (and feature requests), maybe my mind was already in mode for #44 :camel: 

Still, usually when you suggest a change and someone is against it, it makes sense to raise concerns about the change itself. IMO, :+1: can be interpreted as "Hey I like this idea!", which is positive comment. but doesn't require further discussion if you just accept the suggestion. 

:-1: alone is just "Your idea sucks and you should feel bad", but the one who suggested the idea doesn't get **any** feedback on why the idea sucks and/or s/he should feel bad, which is why :-1:'s don't serve any functionality **on it's own**.

**Comment by thejameskyle** [comment]
> :-1: alone is just "Your idea sucks and you should feel bad"

I've seen a lot of comments that are exactly that, although generally far more verbose and mean.

If people will just silently down vote I would prefer that greatly.

**Comment by petetnt** [comment]
That is true too and it's a legitimate issue. Not sure if people would just silently down vote instead of being mean or complaining, but if it would solve that I would prefer down voting to people being mean too by a 100:1 ratio.

But assuming that people would be mean regardless (that's just human nature, it sucks but what can you do), I think that `CONTRIBUTING.md` should apply to the ones contributing to the discussion too. `Don't be dick` clause is a nice addition to any guideline and if people actually read the contribution guidelines (like `dear-github` itself drives forward), it might even be possible.

**Comment by joshmanders** [comment]
Along with silent downvoting, make it so the downvotes are only visible to the owners and collaborators of the repo so you don't have downvote brigading.

**Comment by maartenbusstra** [comment]
+1

(sorry, couldn't help myself)

**Comment by therealbill** [comment]
For some possible avenues explore this thread: https://github.com/waffleio/waffle.io/issues/126#issuecomment-170959056

where we've been discussing a way to do it outside of waiting on GH.

**Comment by alebcay** [comment]
In the meantime, try checking out ZenHub's browser extensions. Among other features, they implement a neat "+1" button next to every comment/issue thread. If others don't have it installed they see a text comment ("+1"), while the plugin automatically sums them up and displays the score at the top of the page.

It's not a perfect solution, but maybe it'll hold you over for the time being.

**Comment by RyanCavanaugh** [comment]
This just went live. :tada:

**Comment by nikolay** [comment]
They just implemented it! https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments
