### ISSUE TITLE
Issue types at creation rather than labels later on

### ISSUE THREAD

**Issue by sohayb** [dear-github/dear-github#59]
I think it would be much more beneficial for the library owners or maintainers if users can assign a label (category) of the issue created as a bug, enhancement, a feature request and so on at creation time so the maintainer can filter that and he can change that category at any point if the reporter mis-categorised it

**Comment by Stargator** [comment]
:+1:

**Comment by jaisonkuriakose** [comment]
I would like to propose a modification to what Sohayb has suggested. I think it would be better if issue submission is kept seperate from issue classification (labeling). This could mean using the simple issue reporting interface that is currently provided by GitHub for issue reporting. For the labeling (categorization), i would suggest to open up the labeling to everyone instead of just developers/ maintainers. This would mean anyone can add a label to a submitted issue. Thus over time, a submitted issue may look something like this:

            Issue                                                                     Label

Need a review button                                                   Enhancement(4), Bug (2), Task (1)

With multiple contributors to the labeling, occurence of mis-classification (mis-categorization/incorrect labeling) can be potentially reduced.
In addition, the time that a contributor takes to label an issue could be recorded (should be visible only to project maintainer). Time spent on the labeling could be a potential indicator of its quality. The advantage is that the contributor does not have to fill out anything additional. A label value with maximum counts and maximum time spent score could potentially have good classification accuracy. 


Potential problems with allowing labeling at the creation time: 
Recent research (e.g. Herzig et al, 2013) has found huge percentage of mis-classifiction in issue data generated with issue trackers that allow labeling/classification at creation time such as Bugzilla. Regarding the developers/maintainers correcting mis-classification, their limited time availability has to be taken in to consideration. An evidence for this is that only about 3% of the Github projects have labelled issue data, the vast majority are unlabelled (source: Cabot et al, 2015). A possible situation in the case of allowing labeling at creation time is that project developers/maintainers may decide to go with what the reporter has labelled and hence the misclassification stays. On the other hand, by allowing the labeling process to evolve independently by the side of of a submitted issue can potentially have advantages, for example, maintainers as well as other contributors know an initially assigned label is just one possible value and that other values are possible. I would say github issue data is in a better situation compared to issue data from many other trackers since the vast majority are unlabelled which means not classified or awaiting classification, not mis-classified.

**Comment by jaisonkuriakose** [comment]
References
1)Herzig, K., Just, S., Zeller, A. (2013). “It’s not a bug, it’s a feature: how misclassification impacts bug prediction”. Proceedings of the international conference on software engineering. USA. Pp.392-401
2)Cabot, J., Izquierdo, J, L, C., Cosentino, V., Rolandi, B., AtlanMod team. (2015). “Exploring the use of labels to categorize issues in open source software projects”. SANER. 
3) Parsons, J., Wand, Y. (2014). “A foundation for open information environments”. Proceedings of the European Conference on Information Systems. Tel Aviv
4) Lukyanenko, R., Parsons, J. (2015). “Principles for modeling user generated content”. Conceptual modeling, pp.432-440
5) Lukyanenko, R., Parsons, J., Wiersma, Y, F. (2014). “The impact of conceptual modeling on dataset completeness: a field experiment”.  Twenty fifth international conference on Information Systems.

**Comment by yvele** [comment]
@jaisonkuriakose Agree with the review button 👍 that allow easy labelling delegation (to users) with control on it!  

PS: Wouldn't it be nice to group labels from colors instead than alphabetically.. People are already semantically grouping labels by colors. Should I create an issue here for that?
