### ISSUE TITLE
Disable reply by email

### ISSUE THREAD

**Issue by mrdoob** [dear-github/dear-github#67]
I'm sure some people like to be able to respond to an issue discussion by email, but personally I would like to be able to disable that feature for my repos.
1. Parsing emails is hard and there is always some left over.
2. People try to attach files on the email. Those files never reach the issues section.
3. Some people have holiday auto responses.

**Comment by cvrebert** [comment]
:+1: 
Or at least make the email bounce back with an error message when someone misguidedly tries to send an attachment. Or add support for attachments.

> Some people have holiday auto responses.

I'm looking at you, freaking Naver.com users!

**Comment by Stargator** [comment]
:+1:

**Comment by zxqfox** [comment]
:+1:

**Comment by asmeurer** [comment]
I think it would go a long way if they simply improved their email reply parsing, so that replies by email don't look like garbage compared to replies made in the web interface.

**Comment by zxqfox** [comment]
Well, this is even better if it goes that way. :+1:

**Comment by scottnonnenberg-signal** [comment]
My biggest problem is that email replies can't use markdown. It's not for the original sender, but for me as a repro owner - comments like this need to be fixed: https://github.com/signalapp/Signal-Desktop/issues/3352#issuecomment-494103543

**Comment by Gadgetoid** [comment]
As far as I can tell, there's still no way to disable this "feature"? The comments here seem to miss the rather more fundamental issues with reply-by-email: beginners posting their telephone numbers.

I have, on more than one occasion, had to edit a response to a GitHub issue to remove personal information such as full names and telephone numbers - contained in email footers and sign-offs - that I'm reasonably sure our customers did not intend to publicly disclose.

Since editing can only hide things under the proverbial rug we are left with a serious issue whereupon private, personally identifiable information is leaked permanently onto the public internet because a beginner misunderstood what replying via email would actually do. Ignoring the myriad ways this might fall afoul of data protection regulations, it surely opens the door for abuse since users are effectively doxing themselves.

Since we deal with GitHub beginners, often posting their very first issue against one of our projects, I've a very strong preference toward completely disabling reply-by-email across our entire GitHub presence to avoid any such incidents.

**Comment by Benjozork** [comment]
This seriously needs to be looked at. We have numerous users leaking personal information without knowing it and getting frustrated when their attachments aren't delivered.

**Comment by bknaysi** [comment]
Has this change been implemented yet? Our team finds automatic email replies on issues particularly annoying. We would love to turn it off entirely. Perhaps a single setting at the repository level would satisfy the demand.

**Comment by zhiliatom** [comment]
> My biggest problem is that email replies can't use markdown. It's not for the original sender, but for me as a repo owner - comments like this need to be fixed: [signalapp/Signal-Desktop#3352 (comment)](https://github.com/signalapp/Signal-Desktop/issues/3352#issuecomment-494103543)

Maybe my querstion is stupid, but how can I reply a comment by email and then It auto show in github. I have a try to reply other's review comment  by email, but can't automatically reply on github website.

**Comment by TieWay59** [comment]
I'm also bothered by the autoreply of email lately. Since GitHub has developed a new featured message system (inbox),  I choose to close most of my access to email. You can  find related options in `settings > notifications > Subscriptions`. I closed `Participating, @mentions and custom` notifications to my mail.

**Comment by tim-rohrer** [comment]
I'll weigh in. The current set up is horrendous. The main problem for us is that the process doesn't retain thread integrity, and each comment emailed in starts a new comment rather that replying to the previous. It makes it very difficult to follow!

**Comment by seanbudd** [comment]
@mrdoob - is there a reason why this was closed? many people are still facing this issue and it is quite frustrating

**Comment by mrdoob** [comment]
GitHub is not going to fix this.

**Comment by seanbudd** [comment]
Are you sure? If you close it this means they definitely won't as it will no longer be tracked

**Comment by mrdoob** [comment]
100% sure

**Comment by worksofliam** [comment]
Please GitHub... let me disable email replies to specific repos or entire orgs.

**Comment by PT-WP** [comment]
Isnt this available? Its so annoying getting these replies...

**Comment by tiagov8** [comment]
Added a related suggestion: https://bettersoftwaresuggestions.com/github/help-me-have-a-clean-message-when-replying-to-an-issue-via-email/
