### ISSUE TITLE
Add duplicate issue search when reporting new issues

### ISSUE THREAD

**Issue by ProLoser** [dear-github/dear-github#98]
https://youtu.be/YYTtPjvA9xk?t=43s

GetSatisfaction and StackOverflow REQUIRE you to search for issues BEFORE you're even allowed to post, because it uses what you're currently typing in as the body or subject of a new issue as search keywords. If you fail to locate any matching queries, you can then click a call to action which converts your search query into the starting basis of your new issue (so you don't have to retype it in).

I've been toying around with the idea of making an open-source hosted project on like heroku where you just oauth with the service and it adds a bot that suggests 3 related issues any time a new issue is created by a non-contributor to the repo (or something like that).

**Comment by ProLoser** [comment]
Technically, if people were interested in collaborating, I'd be interested in helping build a hosted bot-like solution so that people don't have to build their own bots, they simply oauth with this hosted service, similar to how TravisCI and Gitter work.

**Comment by aensley** [comment]
+1, but the title of this issue is confusing. GH won't integrate a third-party to add features officially. But they can emulate the same feature natively.

What GitHub really needs is an automatic issue search when users try to create a new issue. Use just the title and look for similar issues that have already been reported. My team is constantly closing duplicate issues, and a feature like this would help a lot!

We used a similar feature in Trac called the [Duplicate Ticket Search Plugin](https://trac-hacks.org/wiki/DuplicateTicketSearchPlugin).

![trac-relatedtickets](https://cloud.githubusercontent.com/assets/95717/13011123/da9c3d3c-d16a-11e5-92f8-63a8acb9891c.png)

[StackOverflow's implementation](https://stackoverflow.com/questions/ask) also works very well.

![so_suggest](https://cloud.githubusercontent.com/assets/95717/13011143/f8dc288e-d16a-11e5-956f-295c21210650.png)

**Comment by FancyCoder0** [comment]
Hi, I currently noticing this issue which is related to my research work. I have implemented a prototype at [dido.rocks](http://www.dido.rocks) that can be used to detect duplicate issues. It provides a list of all the open issues of one repository and their corresponding duplicate issues, you could login with your GitHub account to check any GitHub repository. It also support checking duplicate issues with a user-inputted issue. Hope that this work is useful to the larger open source community. I am keeping developing this prototype, which is also [open-source on GitHub](https://github.com/FancyCoder0/DIDO). Any kind of feedback is appreciated. Thank you very much!

**Comment by aensley** [comment]
@ProLoser I recommend closing this issue as fixed!
